In [1]:
import pandas as pd

In [2]:
import os

os.getcwd()

'C:\\Users\\Mega Providers'

In [3]:
import os

os.listdir()

[' weelk2.strings.ipynb',
 '.anaconda',
 '.cache',
 '.codex',
 '.conda',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '3D Objects',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'dataframe.csv',
 'Day 3.ipynb',
 'Day4.ipynb',
 'Desktop',
 'Documents',
 'Downloads',
 'exercise1.ipynb',
 'Favorites',
 'file handling.ipynb',
 'function.ipynb',
 'GDP.csv',
 'hello.txt',
 'if,else.ipynb',
 'IntelGraphicsProfiles',
 'lec1',
 'lec1.ipynb',
 'lec1.py',
 'lec3.ipynb',
 'Links',
 'list.ipynb',
 'Local Settings',
 'Loops.ipynb',
 'mark.txt',
 'marks.text',
 'marks.txt',
 'Microsoft',
 'miniconda3',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{0bfab2f9-8083-11f1-9c4a-e95344d97549}.TM.blf',
 'NTUSER.DAT{0bfab2f9-8083-11f1-9c4a-e95344d97549}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{0bfab2f9-8083-11f1-9c4a-e95344d97549}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Numpy AssesmentTest.ipynb',
 'Numpy day3.ipynb',
 'Numpy.day2 arry.ipynb',
 'numpy.ipynb',
 'numpyday1.ipynb',
 'OneDrive',
 'panda.ipynb',
 'pandas Day1.ipynb',
 'Pandas Day2.ipynb',
 'Pictures',
 'PrintHood',
 'PyCharmMiscProject',
 'PycharmProjects',
 'Python AssesmentTest.ipynb',
 'Recent',
 'Rev(day1-5).ipynb',
 'revision.ipynb',
 'revision1.ipynb',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'student.csv',
 'student.txt',
 'students.csv',
 'Templates',
 'Untitled.ipynb',
 'Untitled.xlsx',
 'Videos',
 'week03.exceptionhandling.ipynb',
 'week2.TUPandDIC.ipynb',
 'week2fileio.ipynb',
 'WPS Cloud Files',
 '__pycache__']

In [4]:
df=pd.read_csv("student.csv")

In [5]:
df

     Name  Age        City  Math  English  Science
0     Ali   20      Lahore    85       78       90
1    Sara   21   Islamabad    92       88       95
2   Ahmed   22     Karachi    75       81       79
3  Ayesha   20      Lahore    89       91       87
4   Bilal   23      Multan    68       74       72
5  Fatima   22  Faisalabad    95       93       96
6  Hassan   21    Peshawar    80       77       84
7    Zain   20      Quetta    72       69       75
8    Hina   22      Lahore    90       89       92
9   Usman   23     Karachi    78       80       76

In [6]:
df.head(5)

     Name  Age       City  Math  English  Science
0     Ali   20     Lahore    85       78       90
1    Sara   21  Islamabad    92       88       95
2   Ahmed   22    Karachi    75       81       79
3  Ayesha   20     Lahore    89       91       87
4   Bilal   23     Multan    68       74       72

In [7]:
df.tail(3)

    Name  Age     City  Math  English  Science
7   Zain   20   Quetta    72       69       75
8   Hina   22   Lahore    90       89       92
9  Usman   23  Karachi    78       80       76

In [8]:
df.sample(2)

     Name  Age      City  Math  English  Science
6  Hassan   21  Peshawar    80       77       84
2   Ahmed   22   Karachi    75       81       79

In [9]:
df.shape

(10, 6)

In [10]:
df.columns

Index(['Name', 'Age', 'City', 'Math', 'English', 'Science'], dtype='object')

In [11]:
df.dtypes

Name       object
Age         int64
City       object
Math        int64
English     int64
Science     int64
dtype: object

In [12]:
df.describe()

             Age       Math    English    Science
count  10.000000  10.000000  10.000000  10.000000
mean   21.400000  82.400000  82.000000  84.600000
std     1.173788   9.155448   7.930252   8.720347
min    20.000000  68.000000  69.000000  72.000000
25%    20.250000  75.750000  77.250000  76.750000
50%    21.500000  82.500000  80.500000  85.500000
75%    22.000000  89.750000  88.750000  91.500000
max    23.000000  95.000000  93.000000  96.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   Age      10 non-null     int64
 2   City     10 non-null     object
 3   Math     10 non-null     int64
 4   English  10 non-null     int64
 5   Science  10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

In [14]:
df["Name"]

0       Ali
1      Sara
2     Ahmed
3    Ayesha
4     Bilal
5    Fatima
6    Hassan
7      Zain
8      Hina
9     Usman
Name: Name, dtype: object

In [15]:
df["Math"]

0    85
1    92
2    75
3    89
4    68
5    95
6    80
7    72
8    90
9    78
Name: Math, dtype: int64

In [16]:
df["City"]

0        Lahore
1     Islamabad
2       Karachi
3        Lahore
4        Multan
5    Faisalabad
6      Peshawar
7        Quetta
8        Lahore
9       Karachi
Name: City, dtype: object

In [17]:
df[["Name","Math","Science"]]

     Name  Math  Science
0     Ali    85       90
1    Sara    92       95
2   Ahmed    75       79
3  Ayesha    89       87
4   Bilal    68       72
5  Fatima    95       96
6  Hassan    80       84
7    Zain    72       75
8    Hina    90       92
9   Usman    78       76

In [18]:
df.loc[0]

Name          Ali
Age            20
City       Lahore
Math           85
English        78
Science        90
Name: 0, dtype: object

In [19]:
df.loc[3]

Name       Ayesha
Age            20
City       Lahore
Math           89
English        91
Science        87
Name: 3, dtype: object

In [20]:
df.iloc[2]

Name         Ahmed
Age             22
City       Karachi
Math            75
English         81
Science         79
Name: 2, dtype: object

In [21]:
df.iloc[1:5]

     Name  Age       City  Math  English  Science
1    Sara   21  Islamabad    92       88       95
2   Ahmed   22    Karachi    75       81       79
3  Ayesha   20     Lahore    89       91       87
4   Bilal   23     Multan    68       74       72

In [22]:
df[df["Math"]>80]

     Name  Age        City  Math  English  Science
0     Ali   20      Lahore    85       78       90
1    Sara   21   Islamabad    92       88       95
3  Ayesha   20      Lahore    89       91       87
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92

In [23]:
df[df["City"]=="Lahore"]

     Name  Age    City  Math  English  Science
0     Ali   20  Lahore    85       78       90
3  Ayesha   20  Lahore    89       91       87
8    Hina   22  Lahore    90       89       92

In [24]:
df[df["Age"]>21]

     Name  Age        City  Math  English  Science
2   Ahmed   22     Karachi    75       81       79
4   Bilal   23      Multan    68       74       72
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92
9   Usman   23     Karachi    78       80       76

In [25]:
df[df["English"]>85]

     Name  Age        City  Math  English  Science
1    Sara   21   Islamabad    92       88       95
3  Ayesha   20      Lahore    89       91       87
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92

In [26]:
df[(df["Math"]>80) & (df["Science"]>85)]

     Name  Age        City  Math  English  Science
0     Ali   20      Lahore    85       78       90
1    Sara   21   Islamabad    92       88       95
3  Ayesha   20      Lahore    89       91       87
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92

In [27]:
df[(df["City"]=="Lahore") | (df["City"]=="Karachi")]

     Name  Age     City  Math  English  Science
0     Ali   20   Lahore    85       78       90
2   Ahmed   22  Karachi    75       81       79
3  Ayesha   20   Lahore    89       91       87
8    Hina   22   Lahore    90       89       92
9   Usman   23  Karachi    78       80       76

In [28]:
df[df["Math"]>85]

     Name  Age        City  Math  English  Science
1    Sara   21   Islamabad    92       88       95
3  Ayesha   20      Lahore    89       91       87
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92

In [29]:
df[df["English"]<80]

     Name  Age      City  Math  English  Science
0     Ali   20    Lahore    85       78       90
4   Bilal   23    Multan    68       74       72
6  Hassan   21  Peshawar    80       77       84
7    Zain   20    Quetta    72       69       75

In [30]:
df[df["City"]=="Karachi"]

    Name  Age     City  Math  English  Science
2  Ahmed   22  Karachi    75       81       79
9  Usman   23  Karachi    78       80       76

In [31]:
df[(df["City"]=="Lahore") & (df["Math"]>80)]

     Name  Age    City  Math  English  Science
0     Ali   20  Lahore    85       78       90
3  Ayesha   20  Lahore    89       91       87
8    Hina   22  Lahore    90       89       92

In [32]:
df[(df["City"]=="Karachi") | (df["City"]=="Multan")]

    Name  Age     City  Math  English  Science
2  Ahmed   22  Karachi    75       81       79
4  Bilal   23   Multan    68       74       72
9  Usman   23  Karachi    78       80       76

## Mini Project

In [33]:
df

     Name  Age        City  Math  English  Science
0     Ali   20      Lahore    85       78       90
1    Sara   21   Islamabad    92       88       95
2   Ahmed   22     Karachi    75       81       79
3  Ayesha   20      Lahore    89       91       87
4   Bilal   23      Multan    68       74       72
5  Fatima   22  Faisalabad    95       93       96
6  Hassan   21    Peshawar    80       77       84
7    Zain   20      Quetta    72       69       75
8    Hina   22      Lahore    90       89       92
9   Usman   23     Karachi    78       80       76

In [34]:
df.loc[df["Math"].idxmax()]

Name           Fatima
Age                22
City       Faisalabad
Math               95
English            93
Science            96
Name: 5, dtype: object

In [35]:
df.loc[df["English"].idxmin()]

Name         Zain
Age            20
City       Quetta
Math           72
English        69
Science        75
Name: 7, dtype: object

In [36]:
df["Math"].sum()/10

np.float64(82.4)

In [37]:
df["Science"].sum()/10

np.float64(84.6)

In [38]:
df[df["City"]=="Lahore"]

     Name  Age    City  Math  English  Science
0     Ali   20  Lahore    85       78       90
3  Ayesha   20  Lahore    89       91       87
8    Hina   22  Lahore    90       89       92

In [39]:
df[df["Age"]>21]

     Name  Age        City  Math  English  Science
2   Ahmed   22     Karachi    75       81       79
4   Bilal   23      Multan    68       74       72
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92
9   Usman   23     Karachi    78       80       76

In [40]:
df[(df["Math"]>90)|(df["English"]>90)|(df["Science"]>90)]

     Name  Age        City  Math  English  Science
1    Sara   21   Islamabad    92       88       95
3  Ayesha   20      Lahore    89       91       87
5  Fatima   22  Faisalabad    95       93       96
8    Hina   22      Lahore    90       89       92

In [41]:
df[["Name","Science"]][df["Science"]>85]

     Name  Science
0     Ali       90
1    Sara       95
3  Ayesha       87
5  Fatima       96
8    Hina       92

### Challenge

In [42]:
df["Total"]=df["Math"]+df["English"]+df["Science"]

In [43]:
df

     Name  Age        City  Math  English  Science  Total
0     Ali   20      Lahore    85       78       90    253
1    Sara   21   Islamabad    92       88       95    275
2   Ahmed   22     Karachi    75       81       79    235
3  Ayesha   20      Lahore    89       91       87    267
4   Bilal   23      Multan    68       74       72    214
5  Fatima   22  Faisalabad    95       93       96    284
6  Hassan   21    Peshawar    80       77       84    241
7    Zain   20      Quetta    72       69       75    216
8    Hina   22      Lahore    90       89       92    271
9   Usman   23     Karachi    78       80       76    234

In [44]:
df["Average"]=df["Total"]/3

In [45]:
df

     Name  Age        City  Math  English  Science  Total    Average
0     Ali   20      Lahore    85       78       90    253  84.333333
1    Sara   21   Islamabad    92       88       95    275  91.666667
2   Ahmed   22     Karachi    75       81       79    235  78.333333
3  Ayesha   20      Lahore    89       91       87    267  89.000000
4   Bilal   23      Multan    68       74       72    214  71.333333
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
6  Hassan   21    Peshawar    80       77       84    241  80.333333
7    Zain   20      Quetta    72       69       75    216  72.000000
8    Hina   22      Lahore    90       89       92    271  90.333333
9   Usman   23     Karachi    78       80       76    234  78.000000

In [46]:
df.loc[df["Total"].idxmax()]

Name           Fatima
Age                22
City       Faisalabad
Math               95
English            93
Science            96
Total             284
Average     94.666667
Name: 5, dtype: object

In [47]:
df.loc[df["Average"].idxmax()]

Name           Fatima
Age                22
City       Faisalabad
Math               95
English            93
Science            96
Total             284
Average     94.666667
Name: 5, dtype: object

In [48]:
df[df["Average"]>85]

     Name  Age        City  Math  English  Science  Total    Average
1    Sara   21   Islamabad    92       88       95    275  91.666667
3  Ayesha   20      Lahore    89       91       87    267  89.000000
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
8    Hina   22      Lahore    90       89       92    271  90.333333