### Create a Series

In [1]:
import pandas as pd
marks=pd.Series([80,75,90,88,65])
print(marks)

0    80
1    75
2    90
3    88
4    65
dtype: int64

In [2]:
print(type(marks))
print(marks.size)
print(marks.shape)
print(marks.dtype)

<class 'pandas.core.series.Series'>
5
(5,)
int64

### Create a DataFrame

In [3]:
student={
    "Name":["Ali","Sara","Ahmed","Ayesha"],
    "Age":[22,21,23,20],
    "Marks":[80,75,90,88]
}
df=pd.DataFrame(student)
print(df)

     Name  Age  Marks
0     Ali   22     80
1    Sara   21     75
2   Ahmed   23     90
3  Ayesha   20     88

### View Data

In [4]:
df.head(2)

   Name  Age  Marks
0   Ali   22     80
1  Sara   21     75

In [5]:
df.tail(2)

     Name  Age  Marks
2   Ahmed   23     90
3  Ayesha   20     88

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [7]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   21.500000  83.250000
std     1.290994   6.994045
min    20.000000  75.000000
25%    20.750000  78.750000
50%    21.500000  84.000000
75%    22.250000  88.500000
max    23.000000  90.000000

marks.info() gives information related to variables type and their values(null not null)
while marks.describe() perform some statistical operations on data and gives some valuable insighjts from the data.

In [8]:
print(df["Name"])

0       Ali
1      Sara
2     Ahmed
3    Ayesha
Name: Name, dtype: object

In [9]:
print(df["Marks"])

0    80
1    75
2    90
3    88
Name: Marks, dtype: int64

In [10]:
print(df[["Name","Marks"]])

     Name  Marks
0     Ali     80
1    Sara     75
2   Ahmed     90
3  Ayesha     88

In [11]:
print(df.loc[0])

Name     Ali
Age       22
Marks     80
Name: 0, dtype: object

In [12]:
print(df.loc[2])

Name     Ahmed
Age         23
Marks       90
Name: 2, dtype: object

In [13]:
print(df.iloc[0:2])

   Name  Age  Marks
0   Ali   22     80
1  Sara   21     75

In [14]:
print(df.iloc[0:3])

    Name  Age  Marks
0    Ali   22     80
1   Sara   21     75
2  Ahmed   23     90

### Exercise 1

In [16]:
series1=pd.Series([10,20,30,40,50])
print(series1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Exercise 2

In [17]:
emp={
    "Name":["Ali","Sara","Ahmad"],
    "Age":[25,23,28],
    "City":["Lahore","Islamabad","Karachi"]
}
df1=pd.DataFrame(emp)
print(df1)

    Name  Age       City
0    Ali   25     Lahore
1   Sara   23  Islamabad
2  Ahmad   28    Karachi

### Exercise 3

In [41]:
print(df1.head(2))

   Name  Age       City
0   Ali   25     Lahore
1  Sara   23  Islamabad

In [42]:
print(df1.tail(1))

    Name  Age     City
2  Ahmad   28  Karachi

### Exercise 4

In [20]:
print(df1["Name"])

0      Ali
1     Sara
2    Ahmad
Name: Name, dtype: object

In [21]:
print(df1["Age"])

0    25
1    23
2    28
Name: Age, dtype: int64

### Exercise 5

In [22]:
print(df1.loc[0])

Name       Ali
Age         25
City    Lahore
Name: 0, dtype: object

In [23]:
print(df1.iloc[0])

Name       Ali
Age         25
City    Lahore
Name: 0, dtype: object

In [24]:
print(df1.loc[1])

Name         Sara
Age            23
City    Islamabad
Name: 1, dtype: object

In [25]:
print(df1.loc[2])

Name      Ahmad
Age          28
City    Karachi
Name: 2, dtype: object

In [26]:
print(df1.iloc[1])

Name         Sara
Age            23
City    Islamabad
Name: 1, dtype: object

In [27]:
print(df1.iloc[2])

Name      Ahmad
Age          28
City    Karachi
Name: 2, dtype: object

### Exercise 6

In [28]:
inv={
    "Product":["Laptop","Mouse","Keyboard","Monitor"],
    "Price":[85000,1500,3500,45000],
    "Stock":[12,50,30,8],
}
df2=pd.DataFrame(inv)
print(df2)

    Product  Price  Stock
0    Laptop  85000     12
1     Mouse   1500     50
2  Keyboard   3500     30
3   Monitor  45000      8

In [44]:
print(df2.head(2))

  Product  Price  Stock
0  Laptop  85000     12
1   Mouse   1500     50

In [45]:
print(df2.tail(2))

    Product  Price  Stock
2  Keyboard   3500     30
3   Monitor  45000      8

In [31]:
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  4 non-null      object
 1   Price    4 non-null      int64
 2   Stock    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

In [32]:
print(df2.describe())

              Price      Stock
count      4.000000   4.000000
mean   33750.000000  25.000000
std    39615.863826  19.218047
min     1500.000000   8.000000
25%     3000.000000  11.000000
50%    24250.000000  21.000000
75%    55000.000000  35.000000
max    85000.000000  50.000000

# Mini Project

## Student DataFrame

In [33]:
Student={
    "Name":["Farah","Saba","Iqra","Ali","Rahima","Sara","Tooba","Rabia","Dilavar","Hamza"],
    "Age":[26,27,25,25,26,24,24,25,29,30],
    "City":["Rawalpindi","Gilgit","Quetta","Haripur","Islamabad","Rawalpindi","Rawalpindi","Rawalpindi","Rawalpindi","MUltan"],
    "English":[89,90,76,89,67,99,87,88,76,90],
    "Math":[90,98,87,78,77,76,89,96,95,80],
    "Science":[77,88,90,86,75,85,95,98,97,96]
}
df3=pd.DataFrame(Student)
print(df3)

      Name  Age        City  English  Math  Science
0    Farah   26  Rawalpindi       89    90       77
1     Saba   27      Gilgit       90    98       88
2     Iqra   25      Quetta       76    87       90
3      Ali   25     Haripur       89    78       86
4   Rahima   26   Islamabad       67    77       75
5     Sara   24  Rawalpindi       99    76       85
6    Tooba   24  Rawalpindi       87    89       95
7    Rabia   25  Rawalpindi       88    96       98
8  Dilavar   29  Rawalpindi       76    95       97
9    Hamza   30      MUltan       90    80       96

In [34]:
print(df3.head(5))

     Name  Age        City  English  Math  Science
0   Farah   26  Rawalpindi       89    90       77
1    Saba   27      Gilgit       90    98       88
2    Iqra   25      Quetta       76    87       90
3     Ali   25     Haripur       89    78       86
4  Rahima   26   Islamabad       67    77       75

In [35]:
print(df3.tail(3))

      Name  Age        City  English  Math  Science
7    Rabia   25  Rawalpindi       88    96       98
8  Dilavar   29  Rawalpindi       76    95       97
9    Hamza   30      MUltan       90    80       96

In [36]:
print(df3[["Name","Math"]])

      Name  Math
0    Farah    90
1     Saba    98
2     Iqra    87
3      Ali    78
4   Rahima    77
5     Sara    76
6    Tooba    89
7    Rabia    96
8  Dilavar    95
9    Hamza    80

In [37]:
print(df3.loc[0])

Name            Farah
Age                26
City       Rawalpindi
English            89
Math               90
Science            77
Name: 0, dtype: object

In [38]:
print(df3.loc[4:7])

     Name  Age        City  English  Math  Science
4  Rahima   26   Islamabad       67    77       75
5    Sara   24  Rawalpindi       99    76       85
6   Tooba   24  Rawalpindi       87    89       95
7   Rabia   25  Rawalpindi       88    96       98

In [39]:
print(df3.describe())

             Age    English       Math    Science
count  10.000000  10.000000  10.000000  10.000000
mean   26.100000  85.100000  86.600000  88.700000
std     2.024846   9.290975   8.355969   8.138386
min    24.000000  67.000000  76.000000  75.000000
25%    25.000000  78.750000  78.500000  85.250000
50%    25.500000  88.500000  88.000000  89.000000
75%    26.750000  89.750000  93.750000  95.750000
max    30.000000  99.000000  98.000000  98.000000

In [40]:
print(df3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   Age      10 non-null     int64
 2   City     10 non-null     object
 3   English  10 non-null     int64
 4   Math     10 non-null     int64
 5   Science  10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes
None