In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal", "Fatima"],
    "Age": [20, np.nan, 22, 21, np.nan, 23],
    "City": ["Lahore", "Islamabad", np.nan, "Karachi", "Lahore", "Multan"],
    "Math": [85, 92, np.nan, 89, 68, 95],
    "English": [78, np.nan, 81, 91, 74, 93]
}

df = pd.DataFrame(data)

df

     Name   Age       City  Math  English
0     Ali  20.0     Lahore  85.0     78.0
1    Sara   NaN  Islamabad  92.0      NaN
2   Ahmed  22.0        NaN   NaN     81.0
3  Ayesha  21.0    Karachi  89.0     91.0
4   Bilal   NaN     Lahore  68.0     74.0
5  Fatima  23.0     Multan  95.0     93.0

In [2]:
df.isnull()

    Name    Age   City   Math  English
0  False  False  False  False    False
1  False   True  False  False     True
2  False  False   True   True    False
3  False  False  False  False    False
4  False   True  False  False    False
5  False  False  False  False    False

In [3]:
df.isnull().sum()

Name       0
Age        2
City       1
Math       1
English    1
dtype: int64

In [4]:
df.notnull()

   Name    Age   City   Math  English
0  True   True   True   True     True
1  True  False   True   True    False
2  True   True  False  False     True
3  True   True   True   True     True
4  True  False   True   True     True
5  True   True   True   True     True

In [5]:
df.dropna()

     Name   Age     City  Math  English
0     Ali  20.0   Lahore  85.0     78.0
3  Ayesha  21.0  Karachi  89.0     91.0
5  Fatima  23.0   Multan  95.0     93.0

In [6]:
df.dropna(axis=1)

     Name
0     Ali
1    Sara
2   Ahmed
3  Ayesha
4   Bilal
5  Fatima

In [7]:
df.fillna(0)

     Name   Age       City  Math  English
0     Ali  20.0     Lahore  85.0     78.0
1    Sara   0.0  Islamabad  92.0      0.0
2   Ahmed  22.0          0   0.0     81.0
3  Ayesha  21.0    Karachi  89.0     91.0
4   Bilal   0.0     Lahore  68.0     74.0
5  Fatima  23.0     Multan  95.0     93.0

In [8]:
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [9]:
df

     Name   Age       City  Math  English
0     Ali  20.0     Lahore  85.0     78.0
1    Sara  21.5  Islamabad  92.0      NaN
2   Ahmed  22.0        NaN   NaN     81.0
3  Ayesha  21.0    Karachi  89.0     91.0
4   Bilal  21.5     Lahore  68.0     74.0
5  Fatima  23.0     Multan  95.0     93.0

In [10]:
df["Math"]=df["Math"].fillna(df["Math"].mean())

In [11]:
df["City"]=df["City"].fillna("Unknown")

In [12]:
df["English"]=df["English"].fillna(df["English"].mean())

In [13]:
df

     Name   Age       City  Math  English
0     Ali  20.0     Lahore  85.0     78.0
1    Sara  21.5  Islamabad  92.0     83.4
2   Ahmed  22.0    Unknown  85.8     81.0
3  Ayesha  21.0    Karachi  89.0     91.0
4   Bilal  21.5     Lahore  68.0     74.0
5  Fatima  23.0     Multan  95.0     93.0

In [14]:
df["City"]=df["City"].replace("Lahore","Lahore City")

In [15]:
df

     Name   Age         City  Math  English
0     Ali  20.0  Lahore City  85.0     78.0
1    Sara  21.5    Islamabad  92.0     83.4
2   Ahmed  22.0      Unknown  85.8     81.0
3  Ayesha  21.0      Karachi  89.0     91.0
4   Bilal  21.5  Lahore City  68.0     74.0
5  Fatima  23.0       Multan  95.0     93.0

In [16]:
df.isnull().sum()

Name       0
Age        0
City       0
Math       0
English    0
dtype: int64

In [17]:
df.isnull().sum().sum()

np.int64(0)

In [18]:
df["City"]=df["City"].replace("Karachi","Karachi City")

In [19]:
df

     Name   Age          City  Math  English
0     Ali  20.0   Lahore City  85.0     78.0
1    Sara  21.5     Islamabad  92.0     83.4
2   Ahmed  22.0       Unknown  85.8     81.0
3  Ayesha  21.0  Karachi City  89.0     91.0
4   Bilal  21.5   Lahore City  68.0     74.0
5  Fatima  23.0        Multan  95.0     93.0

In [20]:
df.to_csv("cleaned_students.csv", index=False)

# Questions:

### 1. isnull() display the null Values while isnull().sum() display the total no of null values is each column.

### 2.dropna() is used to remove the entire row with missing values while fillna() is used to fill the missing values with some other value.

### 3.mean value is used to fill the missing values often so that the data distribution remains normal.

### 4.df.dropna(axis=1) is used to remove the columns with missing values.

# Real Data Analyst Task

In [26]:
df["Status"]=df["Math"].apply(
    lambda x: "Pass" if x>=75 else "Fail"
)

In [27]:
df

     Name   Age          City  Math  English Status
0     Ali  20.0   Lahore City  85.0     78.0   Pass
1    Sara  21.5     Islamabad  92.0     83.4   Pass
2   Ahmed  22.0       Unknown  85.8     81.0   Pass
3  Ayesha  21.0  Karachi City  89.0     91.0   Pass
4   Bilal  21.5   Lahore City  68.0     74.0   Fail
5  Fatima  23.0        Multan  95.0     93.0   Pass

In [29]:
df["Status"].value_counts()

Status
Pass    5
Fail    1
Name: count, dtype: int64