In [1]:
import pandas as pd

Students=pd.DataFrame({
    "Student ID":[101,102,103,104],
    "Name":["Ali", "Sara", "Ahmed", "Fatima"]
})

Marks=pd.DataFrame({
    "Student ID":[101,102,103,104],
     "Math": [85, 92, 78, 90],
    "English": [80, 88, 75, 91],
})

Students
Marks

   Student ID  Math  English
0         101    85       80
1         102    92       88
2         103    78       75
3         104    90       91

### Merge DataFrames

In [2]:
df=pd.merge(Students,Marks, on="Student ID")
df

   Student ID    Name  Math  English
0         101     Ali    85       80
1         102    Sara    92       88
2         103   Ahmed    78       75
3         104  Fatima    90       91

In [3]:
df1=pd.merge(Students, Marks, on="Student ID", how="inner")
df1

   Student ID    Name  Math  English
0         101     Ali    85       80
1         102    Sara    92       88
2         103   Ahmed    78       75
3         104  Fatima    90       91

In [4]:
df2=pd.merge(Students, Marks, on="Student ID", how="outer")
df2

   Student ID    Name  Math  English
0         101     Ali    85       80
1         102    Sara    92       88
2         103   Ahmed    78       75
3         104  Fatima    90       91

In [5]:
df3=pd.merge(Students, Marks, on="Student ID", how="right")
df3

   Student ID    Name  Math  English
0         101     Ali    85       80
1         102    Sara    92       88
2         103   Ahmed    78       75
3         104  Fatima    90       91

In [6]:
df2=pd.merge(Students, Marks, on="Student ID", how="left")
df2

   Student ID    Name  Math  English
0         101     Ali    85       80
1         102    Sara    92       88
2         103   Ahmed    78       75
3         104  Fatima    90       91

### Updates DataFrames

In [7]:
Students = pd.DataFrame({
    "Student ID":[101,102,103,104,105],
    "Name":["Ali","Sara","Ahmed","Fatima","Bilal"]
})

Marks = pd.DataFrame({
    "Student ID":[101,102,103,106],
    "Math":[85,92,78,95],
    "English":[80,88,75,90]
})

Students
Marks

   Student ID  Math  English
0         101    85       80
1         102    92       88
2         103    78       75
3         106    95       90

In [8]:
df1=pd.merge(Students,Marks,on="Student ID",how="inner" )
df1

   Student ID   Name  Math  English
0         101    Ali    85       80
1         102   Sara    92       88
2         103  Ahmed    78       75

### inner keeps only the matching ids

In [9]:
df2=pd.merge(Students,Marks,on="Student ID",how="outer" )
df2

   Student ID    Name  Math  English
0         101     Ali  85.0     80.0
1         102    Sara  92.0     88.0
2         103   Ahmed  78.0     75.0
3         104  Fatima   NaN      NaN
4         105   Bilal   NaN      NaN
5         106     NaN  95.0     90.0

### outer keeps all the ids from both data frames

In [10]:
df3=pd.merge(Students,Marks,on="Student ID",how="right" )
df3

   Student ID   Name  Math  English
0         101    Ali    85       80
1         102   Sara    92       88
2         103  Ahmed    78       75
3         106    NaN    95       90

### right join keeps all ids from marks

In [11]:
df4=pd.merge(Students,Marks,on="Student ID",how="left" )
df4

   Student ID    Name  Math  English
0         101     Ali  85.0     80.0
1         102    Sara  92.0     88.0
2         103   Ahmed  78.0     75.0
3         104  Fatima   NaN      NaN
4         105   Bilal   NaN      NaN

### left join keeps all the ids from students

### Concatenate

In [12]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Math": [85, 90]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Fatima"],
    "Math": [78, 92]
})

pd.concat([df1,df2],ignore_index=True)

     Name  Math
0     Ali    85
1    Sara    90
2   Ahmed    78
3  Fatima    92

### Merge with Different Column Names

In [13]:
student_info = pd.DataFrame({
    "ID": [101, 102, 103],
    "Name": ["Ali", "Sara", "Ahmed"]
})

scores = pd.DataFrame({
    "StudentID": [101, 102, 103],
    "Marks": [88, 91, 79]
})

In [14]:
pd.merge(student_info, scores,left_on="ID", right_on="StudentID")

    ID   Name  StudentID  Marks
0  101    Ali        101     88
1  102   Sara        102     91
2  103  Ahmed        103     79

In [15]:
info=pd.DataFrame({
    "StudentID":[40,41,43,45,46],
    "Name":["Ali","Saba","Farah","Iqra","Rabia"],
})

scores=pd.DataFrame({
    "StudentID":[41,42,43,44],
    "Science":[76,78,98,90]
})

info
scores

   StudentID  Science
0         41       76
1         42       78
2         43       98
3         44       90

In [16]:
pd.merge(info,scores,on="StudentID",how="inner")

   StudentID   Name  Science
0         41   Saba       76
1         43  Farah       98

In [17]:
pd.merge(info,scores,on="StudentID",how="outer")

   StudentID   Name  Science
0         40    Ali      NaN
1         41   Saba     76.0
2         42    NaN     78.0
3         43  Farah     98.0
4         44    NaN     90.0
5         45   Iqra      NaN
6         46  Rabia      NaN

In [18]:
pd.merge(info,scores,on="StudentID",how="left")

   StudentID   Name  Science
0         40    Ali      NaN
1         41   Saba     76.0
2         43  Farah     98.0
3         45   Iqra      NaN
4         46  Rabia      NaN

In [19]:
pd.merge(info,scores,on="StudentID",how="right")

   StudentID   Name  Science
0         41   Saba       76
1         42    NaN       78
2         43  Farah       98
3         44    NaN       90

In [20]:
scores1=pd.DataFrame({
    "StudentID":[41,42,43,44],
    "Science":[76,78,98,90]
})

scores2=pd.DataFrame({
    "StudentID":[45,46,47,48],
    "Science":[89,97,98,90]
})

pd.concat([scores1,scores2],ignore_index=True)

   StudentID  Science
0         41       76
1         42       78
2         43       98
3         44       90
4         45       89
5         46       97
6         47       98
7         48       90

In [21]:
Students=pd.DataFrame({
    "Student ID":[101,102,103,104],
    "Name":["Ali", "Sara", "Ahmed", "Fatima"]
})

Marks=pd.DataFrame({
     "Math": [85, 92, 78, 90],
    "English": [80, 88, 75, 91],
})

Students
Marks
pd.concat([Students,Marks],axis=1)

   Student ID    Name  Math  English
0         101     Ali    85       80
1         102    Sara    92       88
2         103   Ahmed    78       75
3         104  Fatima    90       91

In [22]:
Students=pd.DataFrame({
    "Student ID":[101,102,103,104],
    "Name":["Ali", "Sara", "Ahmed", "Fatima"]
})

Marks=pd.DataFrame({
    "Roll_no":[101,102,103,104],
     "Math": [85, 92, 78, 90],
    "English": [80, 88, 75, 91]
})

pd.merge(Students,Marks, left_on="Student ID",right_on="Roll_no")

   Student ID    Name  Roll_no  Math  English
0         101     Ali      101    85       80
1         102    Sara      102    92       88
2         103   Ahmed      103    78       75
3         104  Fatima      104    90       91

### Mini Project

In [23]:
students=pd.DataFrame({
    "StudentID":[41,42,43,44],
    "Name":["Ali","Saba","Farah","Iqra"],
    "City":["Rawalpindi","Mianwali","Islamabad","Rawalpindi"]
})

marks=pd.DataFrame({
    "StudentID":[41,42,43,44],
    "Math":[76,78,98,90],
    "English":[89,90,89,88]
})

attendance=pd.DataFrame({
    "StudentID":[41,42,43,44],
    "percentage_att":[99,95,98,90]
})

df=pd.merge(students,marks,on="StudentID",how="outer").merge(attendance,on="StudentID",how="outer")
df

   StudentID   Name        City  Math  English  percentage_att
0         41    Ali  Rawalpindi    76       89              99
1         42   Saba    Mianwali    78       90              95
2         43  Farah   Islamabad    98       89              98
3         44   Iqra  Rawalpindi    90       88              90

### Challenge

In [24]:
df

   StudentID   Name        City  Math  English  percentage_att
0         41    Ali  Rawalpindi    76       89              99
1         42   Saba    Mianwali    78       90              95
2         43  Farah   Islamabad    98       89              98
3         44   Iqra  Rawalpindi    90       88              90

In [25]:
df["Total"]=df["Math"]+df["English"]

In [26]:
df

   StudentID   Name        City  Math  English  percentage_att  Total
0         41    Ali  Rawalpindi    76       89              99    165
1         42   Saba    Mianwali    78       90              95    168
2         43  Farah   Islamabad    98       89              98    187
3         44   Iqra  Rawalpindi    90       88              90    178

In [27]:
df.sort_values(["Total"],ascending=False)

   StudentID   Name        City  Math  English  percentage_att  Total
2         43  Farah   Islamabad    98       89              98    187
3         44   Iqra  Rawalpindi    90       88              90    178
1         42   Saba    Mianwali    78       90              95    168
0         41    Ali  Rawalpindi    76       89              99    165