In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("student.csv")

In [3]:
print(df)

     Name  Age        City  Math  English  Science
0     Ali   20      Lahore    85       78       90
1    Sara   21   Islamabad    92       88       95
2   Ahmed   22     Karachi    75       81       79
3  Ayesha   20      Lahore    89       91       87
4   Bilal   23      Multan    68       74       72
5  Fatima   22  Faisalabad    95       93       96
6  Hassan   21    Peshawar    80       77       84
7    Zain   20      Quetta    72       69       75
8    Hina   22      Lahore    90       89       92
9   Usman   23     Karachi    78       80       76

In [4]:
df["Total"]=df["Math"]+df["English"]+df["Science"]
df["Average"]=(df["Math"]+df["English"]+df["Science"])/3

In [5]:
df

     Name  Age        City  Math  English  Science  Total    Average
0     Ali   20      Lahore    85       78       90    253  84.333333
1    Sara   21   Islamabad    92       88       95    275  91.666667
2   Ahmed   22     Karachi    75       81       79    235  78.333333
3  Ayesha   20      Lahore    89       91       87    267  89.000000
4   Bilal   23      Multan    68       74       72    214  71.333333
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
6  Hassan   21    Peshawar    80       77       84    241  80.333333
7    Zain   20      Quetta    72       69       75    216  72.000000
8    Hina   22      Lahore    90       89       92    271  90.333333
9   Usman   23     Karachi    78       80       76    234  78.000000

### Selecting Columns

In [6]:
df["Name"]

0       Ali
1      Sara
2     Ahmed
3    Ayesha
4     Bilal
5    Fatima
6    Hassan
7      Zain
8      Hina
9     Usman
Name: Name, dtype: object

In [7]:
df["Total"]

0    253
1    275
2    235
3    267
4    214
5    284
6    241
7    216
8    271
9    234
Name: Total, dtype: int64

### Selecting Rows using iloc

In [8]:
df.iloc[4:9]

     Name  Age        City  Math  English  Science  Total    Average
4   Bilal   23      Multan    68       74       72    214  71.333333
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
6  Hassan   21    Peshawar    80       77       84    241  80.333333
7    Zain   20      Quetta    72       69       75    216  72.000000
8    Hina   22      Lahore    90       89       92    271  90.333333

In [9]:
df.iloc[0:4,0:5]

     Name  Age       City  Math  English
0     Ali   20     Lahore    85       78
1    Sara   21  Islamabad    92       88
2   Ahmed   22    Karachi    75       81
3  Ayesha   20     Lahore    89       91

### Selecting Rows using loc

In [10]:
df.loc[:,["Name","Science"]]

     Name  Science
0     Ali       90
1    Sara       95
2   Ahmed       79
3  Ayesha       87
4   Bilal       72
5  Fatima       96
6  Hassan       84
7    Zain       75
8    Hina       92
9   Usman       76

### Descriptive Statistics

In [11]:
df["Math"].max()

95

In [12]:
df["Science"].min()

72

In [13]:
df["English"].mean()

np.float64(82.0)

In [14]:
df.describe()

             Age       Math    English    Science       Total    Average
count  10.000000  10.000000  10.000000  10.000000   10.000000  10.000000
mean   21.400000  82.400000  82.000000  84.600000  249.000000  83.000000
std     1.173788   9.155448   7.930252   8.720347   24.774539   8.258180
min    20.000000  68.000000  69.000000  72.000000  214.000000  71.333333
25%    20.250000  75.750000  77.250000  76.750000  234.250000  78.083333
50%    21.500000  82.500000  80.500000  85.500000  247.000000  82.333333
75%    22.000000  89.750000  88.750000  91.500000  270.000000  90.000000
max    23.000000  95.000000  93.000000  96.000000  284.000000  94.666667

### Correlation

In [15]:
df.corr(numeric_only=True)

              Age      Math   English   Science     Total   Average
Age      1.000000 -0.244006  0.059683 -0.297430 -0.175760 -0.175760
Math    -0.244006  1.000000  0.883012  0.962496  0.990988  0.990988
English  0.059683  0.883012  1.000000  0.788893  0.924096  0.924096
Science -0.297430  0.962496  0.788893  1.000000  0.960202  0.960202
Total   -0.175760  0.990988  0.924096  0.960202  1.000000  1.000000
Average -0.175760  0.990988  0.924096  0.960202  1.000000  1.000000

In [16]:
df.loc[df["Total"].idxmin()]

Name           Bilal
Age               23
City          Multan
Math              68
English           74
Science           72
Total            214
Average    71.333333
Name: 4, dtype: object

In [17]:
df.loc[df["Total"]>df["Total"].mean()]

     Name  Age        City  Math  English  Science  Total    Average
0     Ali   20      Lahore    85       78       90    253  84.333333
1    Sara   21   Islamabad    92       88       95    275  91.666667
3  Ayesha   20      Lahore    89       91       87    267  89.000000
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
8    Hina   22      Lahore    90       89       92    271  90.333333

In [18]:
df.loc[df["Total"]>250,["Name","City","Total"]]

     Name        City  Total
0     Ali      Lahore    253
1    Sara   Islamabad    275
3  Ayesha      Lahore    267
5  Fatima  Faisalabad    284
8    Hina      Lahore    271

In [20]:
df.loc[df["Age"]>20,["Name","City","Total"]]

     Name        City  Total
1    Sara   Islamabad    275
2   Ahmed     Karachi    235
4   Bilal      Multan    214
5  Fatima  Faisalabad    284
6  Hassan    Peshawar    241
8    Hina      Lahore    271
9   Usman     Karachi    234

### Sorting Data

In [21]:
df.sort_values("Name")

     Name  Age        City  Math  English  Science  Total    Average
2   Ahmed   22     Karachi    75       81       79    235  78.333333
0     Ali   20      Lahore    85       78       90    253  84.333333
3  Ayesha   20      Lahore    89       91       87    267  89.000000
4   Bilal   23      Multan    68       74       72    214  71.333333
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
6  Hassan   21    Peshawar    80       77       84    241  80.333333
8    Hina   22      Lahore    90       89       92    271  90.333333
1    Sara   21   Islamabad    92       88       95    275  91.666667
9   Usman   23     Karachi    78       80       76    234  78.000000
7    Zain   20      Quetta    72       69       75    216  72.000000

In [22]:
df.sort_values("Math", ascending=False)

     Name  Age        City  Math  English  Science  Total    Average
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
1    Sara   21   Islamabad    92       88       95    275  91.666667
8    Hina   22      Lahore    90       89       92    271  90.333333
3  Ayesha   20      Lahore    89       91       87    267  89.000000
0     Ali   20      Lahore    85       78       90    253  84.333333
6  Hassan   21    Peshawar    80       77       84    241  80.333333
9   Usman   23     Karachi    78       80       76    234  78.000000
2   Ahmed   22     Karachi    75       81       79    235  78.333333
7    Zain   20      Quetta    72       69       75    216  72.000000
4   Bilal   23      Multan    68       74       72    214  71.333333

In [23]:
df.sort_values(["Age","Name"])

     Name  Age        City  Math  English  Science  Total    Average
0     Ali   20      Lahore    85       78       90    253  84.333333
3  Ayesha   20      Lahore    89       91       87    267  89.000000
7    Zain   20      Quetta    72       69       75    216  72.000000
6  Hassan   21    Peshawar    80       77       84    241  80.333333
1    Sara   21   Islamabad    92       88       95    275  91.666667
2   Ahmed   22     Karachi    75       81       79    235  78.333333
5  Fatima   22  Faisalabad    95       93       96    284  94.666667
8    Hina   22      Lahore    90       89       92    271  90.333333
4   Bilal   23      Multan    68       74       72    214  71.333333
9   Usman   23     Karachi    78       80       76    234  78.000000

### GroupBy

In [24]:
df.groupby("City")["Total"].mean()

City
Faisalabad    284.000000
Islamabad     275.000000
Karachi       234.500000
Lahore        263.666667
Multan        214.000000
Peshawar      241.000000
Quetta        216.000000
Name: Total, dtype: float64

In [26]:
df.groupby("City")["Total"].max()

City
Faisalabad    284
Islamabad     275
Karachi       235
Lahore        271
Multan        214
Peshawar      241
Quetta        216
Name: Total, dtype: int64

In [27]:
df.groupby("City")["Total"].min()

City
Faisalabad    284
Islamabad     275
Karachi       234
Lahore        253
Multan        214
Peshawar      241
Quetta        216
Name: Total, dtype: int64

In [29]:
df.groupby("City")["Name"].count()

City
Faisalabad    1
Islamabad     1
Karachi       2
Lahore        3
Multan        1
Peshawar      1
Quetta        1
Name: Name, dtype: int64

### Multiple Aggregations

In [30]:
df.groupby("City")["Total"].agg(["mean","min","max","count"])

                  mean  min  max  count
City
Faisalabad  284.000000  284  284      1
Islamabad   275.000000  275  275      1
Karachi     234.500000  234  235      2
Lahore      263.666667  253  271      3
Multan      214.000000  214  214      1
Peshawar    241.000000  241  241      1
Quetta      216.000000  216  216      1

In [32]:
df.groupby("Age")["Math"].agg(["mean","min","max","count"])

          mean  min  max  count
Age
20   82.000000   72   89      3
21   86.000000   80   92      2
22   86.666667   75   95      3
23   73.000000   68   78      2

### Value Counts

In [34]:
df["City"].value_counts()

City
Lahore        3
Karachi       2
Islamabad     1
Multan        1
Faisalabad    1
Peshawar      1
Quetta        1
Name: count, dtype: int64

### lahore has most student  while others have few.

### Unique & Nunique

In [37]:
df["City"].unique()

array(['Lahore', 'Islamabad', 'Karachi', 'Multan', 'Faisalabad',
       'Peshawar', 'Quetta'], dtype=object)

In [38]:
df["City"].nunique()

7

### Renaming Columns

In [43]:
df.rename(columns={
    "Math":"Mathmatics",
    "English":"English_Marks",
    "Science":"Science_Marks"
    
})

,Name,Age,City,Mathmatics,English_Marks,Science_Marks,Total,Average
0,Ali,20,Lahore,85,78,90,253,84.333333
1,Sara,21,Islamabad,92,88,95,275,91.666667
2,Ahmed,22,Karachi,75,81,79,235,78.333333
3,Ayesha,20,Lahore,89,91,87,267,89.000000
4,Bilal,23,Multan,68,74,72,214,71.333333
5,Fatima,22,Faisalabad,95,93,96,284,94.666667
6,Hassan,21,Peshawar,80,77,84,241,80.333333
7,Zain,20,Quetta,72,69,75,216,72.000000
8,Hina,22,Lahore,90,89,92,271,90.333333
9,Usman,23,Karachi,78,80,76,234,78.000000

In [45]:
df = df.rename(columns={
    "Math": "Mathematics",
    "English":"English_Marks",
    "Science":"Science_Marks"
})

### Dropping Columns

In [46]:
df.drop("Average", axis=1)

     Name  Age        City  Mathematics  English_Marks  Science_Marks  Total
0     Ali   20      Lahore           85             78             90    253
1    Sara   21   Islamabad           92             88             95    275
2   Ahmed   22     Karachi           75             81             79    235
3  Ayesha   20      Lahore           89             91             87    267
4   Bilal   23      Multan           68             74             72    214
5  Fatima   22  Faisalabad           95             93             96    284
6  Hassan   21    Peshawar           80             77             84    241
7    Zain   20      Quetta           72             69             75    216
8    Hina   22      Lahore           90             89             92    271
9   Usman   23     Karachi           78             80             76    234

In [47]:
df.drop(["Average", "Total"], axis=1)

     Name  Age        City  Mathematics  English_Marks  Science_Marks
0     Ali   20      Lahore           85             78             90
1    Sara   21   Islamabad           92             88             95
2   Ahmed   22     Karachi           75             81             79
3  Ayesha   20      Lahore           89             91             87
4   Bilal   23      Multan           68             74             72
5  Fatima   22  Faisalabad           95             93             96
6  Hassan   21    Peshawar           80             77             84
7    Zain   20      Quetta           72             69             75
8    Hina   22      Lahore           90             89             92
9   Usman   23     Karachi           78             80             76

### Mini Project

In [52]:
df.groupby("City")["Average"].max()

City
Faisalabad    94.666667
Islamabad     91.666667
Karachi       78.333333
Lahore        90.333333
Multan        71.333333
Peshawar      80.333333
Quetta        72.000000
Name: Average, dtype: float64

In [53]:
df.groupby("City")["Average"].min()

City
Faisalabad    94.666667
Islamabad     91.666667
Karachi       78.000000
Lahore        84.333333
Multan        71.333333
Peshawar      80.333333
Quetta        72.000000
Name: Average, dtype: float64

In [54]:
df.groupby("City")["Mathematics"].mean()

City
Faisalabad    95.0
Islamabad     92.0
Karachi       76.5
Lahore        88.0
Multan        68.0
Peshawar      80.0
Quetta        72.0
Name: Mathematics, dtype: float64

In [56]:
df.groupby("City")["Name"].count()

City
Faisalabad    1
Islamabad     1
Karachi       2
Lahore        3
Multan        1
Peshawar      1
Quetta        1
Name: Name, dtype: int64

In [59]:
df.sort_values("Total", ascending=False)

,Name,Age,City,Mathematics,English_Marks,Science_Marks,Total,Average
5,Fatima,22,Faisalabad,95,93,96,284,94.666667
1,Sara,21,Islamabad,92,88,95,275,91.666667
8,Hina,22,Lahore,90,89,92,271,90.333333
3,Ayesha,20,Lahore,89,91,87,267,89.000000
0,Ali,20,Lahore,85,78,90,253,84.333333
6,Hassan,21,Peshawar,80,77,84,241,80.333333
2,Ahmed,22,Karachi,75,81,79,235,78.333333
9,Usman,23,Karachi,78,80,76,234,78.000000
7,Zain,20,Quetta,72,69,75,216,72.000000
4,Bilal,23,Multan,68,74,72,214,71.333333

In [67]:
df.drop("Average", axis=1)

     Name  Age        City  Mathematics  English_Marks  Science_Marks  Total
0     Ali   20      Lahore           85             78             90    253
1    Sara   21   Islamabad           92             88             95    275
2   Ahmed   22     Karachi           75             81             79    235
3  Ayesha   20      Lahore           89             91             87    267
4   Bilal   23      Multan           68             74             72    214
5  Fatima   22  Faisalabad           95             93             96    284
6  Hassan   21    Peshawar           80             77             84    241
7    Zain   20      Quetta           72             69             75    216
8    Hina   22      Lahore           90             89             92    271
9   Usman   23     Karachi           78             80             76    234

In [68]:
newdf=df[df["City"]=="Lahore"]

In [69]:
newdf

,Name,Age,City,Mathematics,English_Marks,Science_Marks,Total,Average
0,Ali,20,Lahore,85,78,90,253,84.333333
3,Ayesha,20,Lahore,89,91,87,267,89.000000
8,Hina,22,Lahore,90,89,92,271,90.333333

In [71]:
city_report = df.groupby("City").agg({
    "Mathematics": ["mean", "max"],
    "English_Marks": ["mean", "max"],
    "Science_Marks": ["mean", "max"],
    "Total": ["mean", "max", "min"]
})

print(city_report)

           Mathematics     English_Marks     Science_Marks           Total  \
                  mean max          mean max          mean max        mean
City
Faisalabad        95.0  95          93.0  93     96.000000  96  284.000000
Islamabad         92.0  92          88.0  88     95.000000  95  275.000000
Karachi           76.5  78          80.5  81     77.500000  79  234.500000
Lahore            88.0  90          86.0  91     89.666667  92  263.666667
Multan            68.0  68          74.0  74     72.000000  72  214.000000
Peshawar          80.0  80          77.0  77     84.000000  84  241.000000
Quetta            72.0  72          69.0  69     75.000000  75  216.000000


            max  min
City
Faisalabad  284  284
Islamabad   275  275
Karachi     235  234
Lahore      271  253
Multan      214  214
Peshawar    241  241
Quetta      216  216