### Pivot Tables

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali","Sara","Ahmed","Fatima","Ali","Sara"],
    "City": ["Lahore","Karachi","Lahore","Islamabad","Lahore","Karachi"],
    "Subject": ["Math","Math","English","English","Science","Science"],
    "Marks": [85,92,78,88,90,95]
})

df

     Name       City  Subject  Marks
0     Ali     Lahore     Math     85
1    Sara    Karachi     Math     92
2   Ahmed     Lahore  English     78
3  Fatima  Islamabad  English     88
4     Ali     Lahore  Science     90
5    Sara    Karachi  Science     95

In [2]:
pd.pivot_table(df,values="Marks",index="City")

               Marks
City
Islamabad  88.000000
Karachi    93.500000
Lahore     84.333333

In [3]:
pd.pivot_table(df,values="Marks",index="City",columns="Subject")

Subject    English  Math  Science
City
Islamabad     88.0   NaN      NaN
Karachi        NaN  92.0     95.0
Lahore        78.0  85.0     90.0

In [4]:
pd.pivot_table(df,values="Marks",index="Name",columns=["City","Subject"])

City    Islamabad Karachi          Lahore
Subject   English    Math Science English  Math Science
Name
Ahmed         NaN     NaN     NaN    78.0   NaN     NaN
Ali           NaN     NaN     NaN     NaN  85.0    90.0
Fatima       88.0     NaN     NaN     NaN   NaN     NaN
Sara          NaN    92.0    95.0     NaN   NaN     NaN

In [5]:
pd.pivot_table(df,values="Marks",index="City",aggfunc="sum")

           Marks
City
Islamabad     88
Karachi      187
Lahore       253

In [6]:
df.pivot_table(values="Marks",index="City",aggfunc="sum")

           Marks
City
Islamabad     88
Karachi      187
Lahore       253

In [7]:
pd.pivot_table(df,values="Marks",index="City",aggfunc="count")

           Marks
City
Islamabad      1
Karachi        2
Lahore         3

In [8]:
pd.pivot_table(df,values="Marks",index="Subject",aggfunc="mean")

         Marks
Subject
English   83.0
Math      88.5
Science   92.5

In [9]:
pd.pivot_table(df,values="Marks",index="City",aggfunc="max")

           Marks
City
Islamabad     88
Karachi       95
Lahore        90

In [10]:
pd.pivot_table(df,values="Marks",index="Subject",aggfunc="min")

         Marks
Subject
English     78
Math        85
Science     90

In [11]:
pd.pivot_table(df,values="Name",index="City",aggfunc="count")

           Name
City
Islamabad     1
Karachi       2
Lahore        3

### Crosstab

In [12]:
pd.crosstab(df["City"],df["Subject"])

Subject    English  Math  Science
City
Islamabad        1     0        0
Karachi          0     1        1
Lahore           1     1        1

In [13]:
pd.crosstab(df["City"],df["Name"])

Name       Ahmed  Ali  Fatima  Sara
City
Islamabad      0    0       1     0
Karachi        0    0       0     2
Lahore         1    2       0     0

### Date & Time

In [14]:
dates=pd.DataFrame({
    "OrderDate":["2026-05-15","2026-05-17","2026-05-20","2026-05-25","2026-06-15"]
})

dates

    OrderDate
0  2026-05-15
1  2026-05-17
2  2026-05-20
3  2026-05-25
4  2026-06-15

In [15]:
dates["OrderDate"]=pd.to_datetime(dates["OrderDate"])

In [16]:
dates["Year"]=dates["OrderDate"].dt.year

In [17]:
dates["Month"]=dates["OrderDate"].dt.month

In [18]:
dates["Day"]=dates["OrderDate"].dt.day

In [19]:
dates["DayName"]=dates["OrderDate"].dt.day_name()

In [20]:
dates

   OrderDate  Year  Month  Day    DayName
0 2026-05-15  2026      5   15     Friday
1 2026-05-17  2026      5   17     Sunday
2 2026-05-20  2026      5   20  Wednesday
3 2026-05-25  2026      5   25     Monday
4 2026-06-15  2026      6   15     Monday

### String Operations

In [21]:
students = pd.DataFrame({
    "Name":[
        "Ali",
        "SARA",
        "Ahmed",
        "fatima"
    ]
})
students

     Name
0     Ali
1    SARA
2   Ahmed
3  fatima

In [22]:
students["Name"].str.upper()

0       ALI
1      SARA
2     AHMED
3    FATIMA
Name: Name, dtype: object

In [23]:
students["Name"].str.lower()

0       ali
1      sara
2     ahmed
3    fatima
Name: Name, dtype: object

In [24]:
students["Name"].str.contains("m", case=False)

0    False
1    False
2     True
3     True
Name: Name, dtype: bool

In [25]:
students["Name"].str.replace("Ali","Ali Khan")

0    Ali Khan
1        SARA
2       Ahmed
3      fatima
Name: Name, dtype: object

In [26]:
students["Name"].str.len()

0    3
1    4
2    5
3    6
Name: Name, dtype: int64

### Mini Project

In [27]:
SalesData=pd.DataFrame({
    "OrderID":[23,65,67,87,45,98,99,85,54,34],
    "Customer":["Ali","Abid","Subhan","Saba","Farah","Ali","Iman","Haseeb","Aimal","Zafar"],
    "City":["Multan","Quetta","Rawalpindi","Mianwali","Lahore","Karachi","Karachi","Lahore","Islamabad","Rawalpindi"],
    "ProductID":[34,45,76,87,87,45,45,45,34,98],
    "Sales":[2000,3500,600,8000,500,750,400,3000,1000,2500],
    "OrderDate":["2026-07-3","2026-07-6","2026-07-10","2026-07-15","2026-07-15","2026-07-16","2026-07-17","2026-07-20","2026-07-25","2026-07-28"]
})
SalesData

   OrderID Customer        City  ProductID  Sales   OrderDate
0       23      Ali      Multan         34   2000   2026-07-3
1       65     Abid      Quetta         45   3500   2026-07-6
2       67   Subhan  Rawalpindi         76    600  2026-07-10
3       87     Saba    Mianwali         87   8000  2026-07-15
4       45    Farah      Lahore         87    500  2026-07-15
5       98      Ali     Karachi         45    750  2026-07-16
6       99     Iman     Karachi         45    400  2026-07-17
7       85   Haseeb      Lahore         45   3000  2026-07-20
8       54    Aimal   Islamabad         34   1000  2026-07-25
9       34    Zafar  Rawalpindi         98   2500  2026-07-28

In [28]:
SalesData.to_csv("Sales.csv", index=False)

In [29]:
SalesData["OrderDate"]=pd.to_datetime(SalesData["OrderDate"])

In [30]:
SalesData["Year"]=SalesData["OrderDate"].dt.year

In [31]:
SalesData["Month"]=SalesData["OrderDate"].dt.month

In [32]:
SalesData["Day"]=SalesData["OrderDate"].dt.day

In [33]:
SalesData["DayName"]=SalesData["OrderDate"].dt.day_name()

In [34]:
SalesData

,OrderID,Customer,City,ProductID,Sales,OrderDate,Year,Month,Day,DayName
0,23,Ali,Multan,34,2000,2026-07-03,2026,7,3,Friday
1,65,Abid,Quetta,45,3500,2026-07-06,2026,7,6,Monday
2,67,Subhan,Rawalpindi,76,600,2026-07-10,2026,7,10,Friday
3,87,Saba,Mianwali,87,8000,2026-07-15,2026,7,15,Wednesday
4,45,Farah,Lahore,87,500,2026-07-15,2026,7,15,Wednesday
5,98,Ali,Karachi,45,750,2026-07-16,2026,7,16,Thursday
6,99,Iman,Karachi,45,400,2026-07-17,2026,7,17,Friday
7,85,Haseeb,Lahore,45,3000,2026-07-20,2026,7,20,Monday
8,54,Aimal,Islamabad,34,1000,2026-07-25,2026,7,25,Saturday
9,34,Zafar,Rawalpindi,98,2500,2026-07-28,2026,7,28,Tuesday

In [35]:
SalesData.pivot_table(values="Sales",index="City",aggfunc="sum")

            Sales
City
Islamabad    1000
Karachi      1150
Lahore       3500
Mianwali     8000
Multan       2000
Quetta       3500
Rawalpindi   3100

In [36]:
SalesData.pivot_table(values="Sales",index="ProductID",aggfunc="mean")

            Sales
ProductID
34         1500.0
45         1912.5
76          600.0
87         4250.0
98         2500.0

In [37]:
pd.crosstab(SalesData["City"],SalesData["ProductID"])

ProductID   34  45  76  87  98
City
Islamabad    1   0   0   0   0
Karachi      0   2   0   0   0
Lahore       0   1   0   1   0
Mianwali     0   0   0   1   0
Multan       1   0   0   0   0
Quetta       0   1   0   0   0
Rawalpindi   0   0   1   0   1

In [38]:
SalesData["Customer"].str.upper()

0       ALI
1      ABID
2    SUBHAN
3      SABA
4     FARAH
5       ALI
6      IMAN
7    HASEEB
8     AIMAL
9     ZAFAR
Name: Customer, dtype: object

In [39]:
SalesData["Customer"].str.replace("Aimal","Eshal")

0       Ali
1      Abid
2    Subhan
3      Saba
4     Farah
5       Ali
6      Iman
7    Haseeb
8     Eshal
9     Zafar
Name: Customer, dtype: object

In [40]:
SalesData.sort_values("Sales",ascending=False)

,OrderID,Customer,City,ProductID,Sales,OrderDate,Year,Month,Day,DayName
3,87,Saba,Mianwali,87,8000,2026-07-15,2026,7,15,Wednesday
1,65,Abid,Quetta,45,3500,2026-07-06,2026,7,6,Monday
7,85,Haseeb,Lahore,45,3000,2026-07-20,2026,7,20,Monday
9,34,Zafar,Rawalpindi,98,2500,2026-07-28,2026,7,28,Tuesday
0,23,Ali,Multan,34,2000,2026-07-03,2026,7,3,Friday
8,54,Aimal,Islamabad,34,1000,2026-07-25,2026,7,25,Saturday
5,98,Ali,Karachi,45,750,2026-07-16,2026,7,16,Thursday
2,67,Subhan,Rawalpindi,76,600,2026-07-10,2026,7,10,Friday
4,45,Farah,Lahore,87,500,2026-07-15,2026,7,15,Wednesday
6,99,Iman,Karachi,45,400,2026-07-17,2026,7,17,Friday